version: "3.8"
services:
  # Nginx servers
  nginx-backend:
    image: nginx
    container_name: autofix-nginx-backend-container
    restart: always
    ports:
      - 80:80
    volumes:
      - ./backend.conf:/etc/nginx/nginx.conf
    networks:
      - autofix-backend-network
    depends_on:
      - spring1
      - spring2
      - spring3      
  nginx-frontend:
    image: nginx
    container_name: autofix-nginx-frontend-container
    restart: always
    ports:
      - 8070:8070
    volumes:
      - ./frontend.conf:/etc/nginx/nginx.conf
    networks:
      - autofix-frontend-network
    depends_on:      
      - react1
      - react2
      - react3

  mysql:
    container_name: autofix-mysql-container
    image: mysql
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - autofix-mysql-volume:/var/lib/mysql
    networks:
      - autofix-backend-network
    environment:
      MYSQL_ROOT_PASSWORD: 3220mA++
    ports:
      - 3307:3306   
  spring1:
    container_name: autofix-backend-container-1
    image: fabianlizama/autofix-backend
    ports:
      - 8091:8079
    environment:
      DB_HOST: autofix-mysql-container
      MYSQL_PASSWORD: 3220mA++
    networks:
      - autofix-backend-network
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - mysql
  spring2:
    container_name: autofix-backend-container-2
    image: fabianlizama/autofix-backend
    ports:
      - 8092:8079
    environment:
      DB_HOST: autofix-mysql-container
      MYSQL_PASSWORD: 3220mA++
    networks:
      - autofix-backend-network
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - mysql
  spring3:
    container_name: autofix-backend-container-3
    image: fabianlizama/autofix-backend
    ports:
      - 8093:8079
    environment:
      DB_HOST: autofix-mysql-container
      MYSQL_PASSWORD: 3220mA++
    networks:
      - autofix-backend-network
    deploy:
      restart_policy:
        condition: on-failure
  react1:
    container_name: autofix-frontend-container-1
    image: fabianlizama/autofix-frontend
    ports:
      - 3001:3000
    networks:
      - autofix-frontend-network
    deploy:
      restart_policy:
        condition: on-failure
  react2:
    container_name: autofix-frontend-container-2
    image: fabianlizama/autofix-frontend
    ports:
      - 3002:3000
    networks:
      - autofix-frontend-network
    deploy:
      restart_policy:
        condition: on-failure
  react3:
    container_name: autofix-frontend-container-3
    image: fabianlizama/autofix-frontend
    networks:
      - autofix-frontend-network
    ports:
      - 3003:3000
    deploy:
      restart_policy:
        condition: on-failure
volumes:
  autofix-mysql-volume:
networks:
  autofix-frontend-network:
  autofix-backend-network: