pipeline{
    agent any
    stages{
        stage("Build Frontend"){
            steps{
                checkout scmGit(branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/FabianLizama/autofix-tingeso']])
                dir("landing"){
                    bat "npm install"
                    bat "npm run build"
                }
            }
        }
        stage("Build and Push Docker Image"){
            steps{
                dir("landing"){
                    script{
                         withDockerRegistry(credentialsId: 'docker-credentials'){
                            bat "docker build -t fabianlizama/autofix-frontend ."
                            bat "docker push fabianlizama/autofix-frontend"
                        }
                    }                    
                }
            }
        }
    }
}
